### ISSUE TITLE
Cache busting

### ISSUE THREAD

**Issue by illycz** [ianrose/deventy#9]
Do you plan integrate some logic for assets revisioning?
Ideally solution which:
- generate hashes for css and js files
- generate hashes for images (in html and css too)
- generate manifest file for mapping (for use case where 11ty is only templates generator)

Thanks!

**Comment by ianrose** [comment]
@illycz asset revisioning could be considered for addition. How assets are hashed and referenced could be done differently.

For example two CLIs:
1. https://github.com/lukasoppermann/node-file-rev
1. https://github.com/L8D/rev-all 

`rev-all` is nice because it does both the hashing and reference updating. `node-file-rev` allows more fine grained/manual control of reference updating via the templates and a manifest.

At the moment I'm considering making an `examples` folder or branches of different ways/tools could be integrated. To keep `master` as a minimal starting point.

If you need assets revisioning now you could do something like:

1. Install `rev-all`
```
$ npm install rev-all --save
```

2. Add npm script to run the cli and add that as part of the build script. In this example a new folder `deploy` is generated with hashed assets.
```json
...,
"rev": "rev-all dist deploy --dont-rename html",
...,
"build": "run-s clean styles:prod scripts:prod eleventy:default rev --print-label"
```

3. Update `.gitignore`
```
...
deploy
```
Also something to consider if you are flexible with your host. [Netlify](https://www.netlify.com/) bust cache for you on deploys.

**Comment by illycz** [comment]
Fantastic, thanks for your reply, I will look at it...

**Comment by illycz** [comment]
@ianrose everything work as expected.
Only one little change, deploy folder need to be cleared too so I edit clear task: `"clean": "rm -rf dist deploy"`.

You can close if you want...
